v0.4
xakepon/java-explore-with-me pull request #3
Opened 2024-08-20 08:47 UTC by xakepon

2024-08-22 08:08 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-08-22 08:08 UTC, LexLippi commented on ewm-stat-service/stat-service/src/main/java/ru/practicum/mapper/EndpointHitMapper.java
>  public final class EndpointHitMapper {
Если это класс-помощник, то у него должен быть приватный конструктор без аргументов

2024-08-22 08:08 UTC, LexLippi commented on ewm-stat-service/stat-service/src/main/java/ru/practicum/api/StatServiceImpl.java
> +        return viewStat.isEmpty() ? Collections.emptyList() : viewStat;
Зачем этот тернарник?
Если список пустой, то он и так вернет пустой список

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +	status VARCHAR(30),
Может быть `null`?

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +);
А `primary key` у этой таблицы какой?

https://stackoverflow.com/questions/39649981/why-is-it-a-bad-idea-to-have-a-table-without-a-primary-key

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +	pinned BOOLEAN,
могут быть `null`?

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +	paid BOOLEAN DEFAULT FALSE,
могут быть `null`?

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS participation CASCADE;
Этого не должно быть в скрипте инициализации базы данных, иначе мы при каждом релизе будем дропать данные пользователей и пользоваться нашим приложением никто не будет

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_location PRIMARY KEY (id)
Тут что-то с отступами не то

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/statLog/StatisticInterceptor.java
> +        return true;
Странный метод, который всегда возвращает `true`, но допустим)

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/statLog/StatisticInterceptor.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Вот это хотелось бы в общую константу проекта вынести, а не в каждом классе по отдельности ее хранить

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/UserMapper.java
> +public final class UserMapper {
Не хватает приватного конструктора без аргументов для класса-помощника

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/ParticipationMapper.java
> +                .count();
Можно использовать тернарный оператор

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/ParticipationMapper.java
> +public final class ParticipationMapper {
Не хватает приватного конструктора без аргументов

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/LocationMapper.java
> +public final class LocationMapper {
Приватный конструктор без аргументов

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/EventMapper.java
> +public final class EventMapper {
Приватный конструктор без аргументов

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/CompilationMapper.java
> +public final class CompilationMapper {
Приватный конструктор без аргументов

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/CommentMapper.java
> +public final class CommentMapper {
Это зачем?

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/mapper/CategoryMapper.java
> +public final class CategoryMapper {
Приватный конструктор без аргументов

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/enums/SortState.java
> +        return Optional.empty();
Можно переписать используя `Stream API`

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/enums/RequestStatus.java
> +    public static Optional<RequestStatus> from(String stringRequestStatus) {
Аналогично тому, что писал

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/enums/PrivateStateAction.java
> +    public static Optional<PrivateStateAction> from(String stringStateAction) {
Аналогично тому, что писал

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/enums/ParticipationStatus.java
> +    public static Optional<ParticipationStatus> from(String stringStatus) {
Аналогично тому, что писал

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/enums/EventState.java
> +    public static Optional<EventState> from(String stringState) {
Аналогично тому, что писал

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/enums/ApiStatus.java
> +    public static Optional<ApiStatus> from(String stringStatus) {
Аналогично тому, что писал

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/common/enums/AdminStateAction.java
> +    public static Optional<AdminStateAction> from(String stringStateAction) {
Аналогично тому, что писал

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/api/responseDto/CommentDto.java
> +public class CommentDto {
Это зачем?

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/api/publicAPI/event/PublicEventServiceImpl.java
> +        if (sortState.isPresent()) {
Можно инвертировать условный оператор и ветка `else` будет не нужна

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/api/publicAPI/event/PublicEventServiceImpl.java
> +            if (action != null) {
Можно инвертировать условный оператор и ветка `else` будет не нужна

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/api/publicAPI/event/PublicEventServiceImpl.java
> +        if (sortState.isPresent()) {
По возможности лучше использовать `ifPresentOrElse`

2024-08-22 08:08 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/api/publicAPI/comment/PublicCommentController.java
> +public class PublicCommentController {
Зачем?

2024-08-22 08:28 UTC, xakepon commented on ewm-service/src/main/resources/schema.sql
> +);
сделал

2024-08-22 08:34 UTC, xakepon commented on ewm-service/src/main/resources/schema.sql
> +	pinned BOOLEAN,
сделал

2024-08-22 08:34 UTC, xakepon commented on ewm-service/src/main/resources/schema.sql
> +	paid BOOLEAN DEFAULT FALSE,
сделал

2024-08-22 08:34 UTC, xakepon commented on ewm-service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS participation CASCADE;
сделал

2024-08-22 08:39 UTC, xakepon commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_location PRIMARY KEY (id)
надеюсь я правильно понял про отступы, сделал как пишут в тырнете в традиционном виде

2024-08-22 08:42 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/statLog/StatisticInterceptor.java
> +        return true;
да чтобы запросы обрабатывались всегда, используется для сбора статистики о запросах...

2024-08-22 08:45 UTC, xakepon commented on ewm-stat-service/stat-service/src/main/java/ru/practicum/mapper/EndpointHitMapper.java
>  public final class EndpointHitMapper {
сделал

2024-08-22 09:50 UTC, xakepon commented on ewm-service/src/main/resources/schema.sql
> +	status VARCHAR(30),
сделал

2024-08-22 10:35 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/api/publicAPI/comment/PublicCommentController.java
> +public class PublicCommentController {
это уже готовил структуру проекта под третью часть диплома, чтобы потом меньше работы было, надо было комменты оставить внутри для чего делал

2024-08-22 10:41 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/api/responseDto/CommentDto.java
> +public class CommentDto {
это уже готовил структуру проекта под третью часть диплома, чтобы потом меньше работы было, надо было комменты оставить внутри для чего делал

2024-08-22 10:42 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/statLog/StatisticInterceptor.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
сделал, реализовал интерфейс в двух модулях где используется данная константа

2024-08-22 10:43 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/UserMapper.java
> +public final class UserMapper {
сделал

2024-08-22 10:47 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/ParticipationMapper.java
> +                .count();
сделал

2024-08-22 10:47 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/ParticipationMapper.java
> +public final class ParticipationMapper {
сделал

2024-08-22 10:51 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/LocationMapper.java
> +public final class LocationMapper {
сделал

2024-08-22 10:51 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/EventMapper.java
> +public final class EventMapper {
сделал

2024-08-22 10:51 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/CompilationMapper.java
> +public final class CompilationMapper {
сделал

2024-08-22 10:52 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/CommentMapper.java
> +public final class CommentMapper {
это уже готовил структуру проекта под третью часть диплома, чтобы потом меньше работы было, надо было комменты оставить внутри для чего делал

2024-08-22 10:52 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/mapper/CategoryMapper.java
> +public final class CategoryMapper {
сделал

2024-08-22 10:56 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/enums/SortState.java
> +        return Optional.empty();
сделал

2024-08-22 11:25 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/enums/RequestStatus.java
> +    public static Optional<RequestStatus> from(String stringRequestStatus) {
сделал

2024-08-22 11:25 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/enums/PrivateStateAction.java
> +    public static Optional<PrivateStateAction> from(String stringStateAction) {
сделал

2024-08-22 11:25 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/enums/ParticipationStatus.java
> +    public static Optional<ParticipationStatus> from(String stringStatus) {
сделал

2024-08-22 11:25 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/enums/EventState.java
> +    public static Optional<EventState> from(String stringState) {
сделал

2024-08-22 11:25 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/enums/ApiStatus.java
> +    public static Optional<ApiStatus> from(String stringStatus) {
сделал

2024-08-22 11:25 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/common/enums/AdminStateAction.java
> +    public static Optional<AdminStateAction> from(String stringStateAction) {
сделал

2024-08-22 11:38 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/api/publicAPI/event/PublicEventServiceImpl.java
> +        if (sortState.isPresent()) {
ок

2024-08-22 11:42 UTC, xakepon commented on ewm-service/src/main/java/ru/practicum/api/publicAPI/event/PublicEventServiceImpl.java
> +            if (action != null) {
ок

2024-08-23 11:03 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи с заключительным этапом диплома!

2024-08-23 11:09 UTC, merged